In [185]:
import pandas as pd
from os.path import exists
pd.set_option('display.max_rows', 500)

In [186]:
# Set up dataframe
num_charts = 7
df_cols = ['Base Calc'] + ['Chart '+str(x+1) for x in range(7)] + ['Final Calc']
venus_rising_df = pd.DataFrame(columns=df_cols).fillna(0)


venus_rising_data_dict =[[1,1,10],
                          [2,3,16],
                          [3,1,16],
                          [4,1,8],
                          [5,1,12], #row 8 to 9 is 6st, row 9 to 10 is 2 st, ctnd
                          [6,1,10], #we're back to 2 and 4 again
                          [7,1,21]] #weird, let's just make some manual row_adds for chart 5&7
special_increases = {5:[14,2,4,2,4,2,4,2,6,2,6,2],
                     7:[14,2,4,4,4,2,4,6,4,4,6,2,4,2,4,2,4,2,4,2,2]}

## Create dat functional loop

In [187]:
def venus_pattern_loop(chart_num, reps, rows):
    curr_chart = f'Chart {chart_num}'
    prev_chart = f'Chart {chart_num-1}' if chart_num != 1 else 'Base Calc'
    for rep in range(reps):
        for row_val in range(rows):
            row_num = row_val+(rep*rows)
            if chart_num in [5,7]:
                row_add = special_increases[chart_num][row_val]
            elif row_num % 2 == 0:
                row_add = 4
            else:
                row_add = 2
#             print(rep, row_val, row_num, row_add)
            if row_num == 0:
                last_row_num = venus_rising_df[prev_chart].last_valid_index()
                last_row_st = venus_rising_df.loc[last_row_num,prev_chart]
            else:
                last_row_st = venus_rising_df.loc[row_num-1,curr_chart]

            num_row_st = last_row_st + row_add
            venus_rising_df.loc[row_num,curr_chart] = int(num_row_st)
    ret_msg = f"{curr_chart}: {venus_rising_df[curr_chart].last_valid_index()+1} rows."
    print(ret_msg)

## Set up dataframe

In [188]:
curr_chart = 'Chart 1'
# Before automating the calculations, gotta manually set up the proj!
cast_on_st = 3
garter_rows = 12

# this will be added
garter_tab_st = cast_on_st * garter_rows

c1_setup_row = 13

# add prev values to Base Calc
venus_rising_df.loc[0,'Base Calc'] = garter_tab_st
venus_rising_df.loc[1,'Base Calc'] = c1_setup_row

## Populate dataframe with st values

In [189]:
if pd.notnull(venus_rising_df.loc[0,'Final Calc']):
    print('Already done!')
else:
    for sheet_num, rows, reps in venus_rising_data_dict:
        venus_pattern_loop(sheet_num, rows, reps)

    last_df_row_num = venus_rising_df[f"Chart {num_charts}"].last_valid_index()
    last_df_row_st = venus_rising_df.loc[last_df_row_num,f"Chart {num_charts}"]
    venus_rising_df.loc[0,'Final Calc'] = last_df_row_st
    print('Done!')

    venus_rising_df = venus_rising_df.fillna(0)

Chart 1: 10 rows.
Chart 2: 48 rows.
Chart 3: 16 rows.
Chart 4: 8 rows.
Chart 5: 12 rows.
Chart 6: 10 rows.
Chart 7: 21 rows.
Done!

In [190]:
venus_rising_data_dict =[[1,1,10],
                          [2,3,16],
                          [3,1,16],
                          [4,1,8],
                          [5,1,12], #row 8 to 9 is 6st, row 9 to 10 is 2 st, ctnd
                          [6,1,10], #we're back to 2 and 4 again
                          [7,1,21]] #weird, let's just make some manual row_adds for chart 5&7
special_increases = {5:[4,2,4,2,4,2,4,2,6,2,6,2],
                     7:[4,2,4,4,4,2,4,6,4,4,6,2,4,2,4,2,4,2,4,2,2]}

## Create dat functional loop

In [191]:
def venus_pattern_loop(chart_num, reps, rows):
    curr_chart = f'Chart {chart_num}'
    prev_chart = f'Chart {chart_num-1}' if chart_num != 1 else 'Base Calc'
    for rep in range(reps):
        for row_val in range(rows):
            row_num = row_val+(rep*rows)
            if chart_num in [5,7]:
                row_add = special_increases[chart_num][row_val]
            elif row_num % 2 == 0:
                row_add = 4
            else:
                row_add = 2
#             print(rep, row_val, row_num, row_add)
            if row_num == 0:
                last_row_num = venus_rising_df[prev_chart].last_valid_index()
                last_row_st = venus_rising_df.loc[last_row_num,prev_chart]
            else:
                last_row_st = venus_rising_df.loc[row_num-1,curr_chart]

            num_row_st = last_row_st + row_add
            venus_rising_df.loc[row_num,curr_chart] = int(num_row_st)
    ret_msg = f"{curr_chart}: {venus_rising_df[curr_chart].last_valid_index()+1} rows."
    print(ret_msg)

## Set up dataframe

In [192]:
curr_chart = 'Chart 1'
# Before automating the calculations, gotta manually set up the proj!
cast_on_st = 3
garter_rows = 12

# this will be added
garter_tab_st = cast_on_st * garter_rows

c1_setup_row = 13

# add prev values to Base Calc
venus_rising_df.loc[0,'Base Calc'] = garter_tab_st
venus_rising_df.loc[1,'Base Calc'] = c1_setup_row

## Populate dataframe with st values

In [193]:
if pd.notnull(venus_rising_df.loc[0,'Final Calc']):
    print('Already done!')
else:
    for sheet_num, rows, reps in venus_rising_data_dict:
        venus_pattern_loop(sheet_num, rows, reps)

    last_df_row_num = venus_rising_df[f"Chart {num_charts}"].last_valid_index()
    last_df_row_st = venus_rising_df.loc[last_df_row_num,f"Chart {num_charts}"]
    venus_rising_df.loc[0,'Final Calc'] = last_df_row_st
    print('Done!')

    venus_rising_df = venus_rising_df.fillna(0)

Already done!

In [194]:
venus_rising_df

,Base Calc,Chart 1,Chart 2,Chart 3,Chart 4,Chart 5,Chart 6,Chart 7,Final Calc
0,36,17,47,191,239,273,313,353,421
1,13,19,49,193,241,275,315,355,0
2,0,23,53,197,245,279,319,359,0
3,0,25,55,199,247,281,321,363,0
4,0,29,59,203,251,285,325,367,0
5,0,31,61,205,253,287,327,369,0
6,0,35,65,209,257,291,331,373,0
7,0,37,67,211,259,293,333,379,0
8,0,41,71,215,0,299,337,383,0
9,0,43,73,217,0,301,339,387,0
10,0,0,77,221,0,307,0,393,0
11,0,0,79,223,0,309,0,395,0
12,0,0,83,227,0,0,0,399,0
13,0,0,85,229,0,0,0,401,0
14,0,0,89,233,0,0,0,405,0
15,0,0,91,235,0,0,0,407,0
16,0,0,95,0,0,0,0,411,0
17,0,0,97,0,0,0,0,413,0
18,0,0,101,0,0,0,0,417,0
19,0,0,103,0,0,0,0,419,0
20,0,0,107,0,0,0,0,421,0
21,0,0,109,0,0,0,0,0,0
22,0,0,113,0,0,0,0,0,0
23,0,0,115,0,0,0,0,0,0
24,0,0,119,0,0,0,0,0,0
25,0,0,121,0,0,0,0,0,0
26,0,0,125,0,0,0,0,0,0
27,0,0,127,0,0,0,0,0,0
28,0,0,131,0,0,0,0,0,0
29,0,0,133,0,0,0,0,0,0
30,0,0,137,0,0,0,0,0,0
31,0,0,139,0,0,0,0,0,0
32,0,0,143,0,0,0,0,0,0
33,0,0,145,0,0,0,0,0,0
34,0,0,149,0,0,0,0,0,0
35,0,0,151,0,0,0,0,0,0
36,0,0,155,0,0,0,0,0,0
37,0,0,157,0,0,0,0,0,0
38,0,0,161,0,0,0,0,0,0
39,0,0,163,0,0,0,0,0,0
40,0,0,167,0,0,0,0,0,0
41,0,0,169,0,0,0,0,0,0
42,0,0,173,0,0,0,0,0,0
43,0,0,175,0,0,0,0,0,0
44,0,0,179,0,0,0,0,0,0
45,0,0,181,0,0,0,0,0,0
46,0,0,185,0,0,0,0,0,0
47,0,0,187,0,0,0,0,0,0

## Calculator Prep Work

In [195]:
total_pattern_st = sum(venus_rising_df.sum())

In [196]:
def get_time_stats(knit_data, st_per_min):
    for k,v in knit_data.items():
        total_min = v['st'] / st_per_min
        total_hr = round(total_min/60,2)
        knit_data[k]['hr'] = int(total_hr)
    return knit_data

In [197]:
def get_perc_stats(knit_data):
    completed_perc = round(100*knit_data['completed']['st']/knit_data['pattern']['st'],2)
    remaining_perc = round(100*knit_data['remaining']['st']/knit_data['pattern']['st'],2)
    knit_data['completed']['perc'] = completed_perc
    knit_data['remaining']['perc'] = remaining_perc
    return knit_data

In [198]:
def calculate_progress(which_date, which_chart, which_rep, which_row, st_per_min):    
    # this will hold total stitches, but i'm pre-adding our set up row sts.
    total_completed_st = sum(venus_rising_df.loc[:,'Base Calc'])

    for chart_num in range(1,which_chart):
        st_done_in_prev_chart = sum(venus_rising_df.loc[:,f"Chart {chart_num}"])
        total_completed_st += st_done_in_prev_chart

    # Since chart #2 is the only one with reps, I'm only accounting for that.
    # (that is, which_rep-1 will equal zero for all other charts with 1 rep)
    curr_chart_last_row = which_row + (16*(which_rep-1))
    st_done_in_curr_chart = sum(venus_rising_df.loc[:curr_chart_last_row,f"Chart {which_chart}"])

    total_completed_st += st_done_in_curr_chart
    #---------------

    knit_data = {'pattern':{'st':int(total_pattern_st)},
                 'completed':{'st':int(total_completed_st)},
                 'remaining':{'st':int(total_pattern_st - total_completed_st)}}

    knit_data = get_time_stats(knit_data, st_per_min)
    knit_data = get_perc_stats(knit_data)
    
    vals =   {'Date': which_date,
             'Chart': which_chart,
               'Rep': which_rep,
               'Row': which_row,
            'St/Min': st_per_min,
      'Pattern (st)': knit_data['pattern']['st'],
     'Pattern (hrs)': knit_data['pattern']['hr'],
    'Completed (st)': knit_data['completed']['st'],
   'Completed (hrs)': knit_data['completed']['hr'],
  'Completed (perc)': knit_data['completed']['perc'],
    'Remaining (st)': knit_data['remaining']['st'],
   'Remaining (hrs)': knit_data['remaining']['hr'],
  'Remaining (perc)': knit_data['remaining']['perc'],
  'timestamp': pd.Timestamp.now()}
    
    return vals

In [199]:
def give_me_info_on(which_chart, which_rep, which_row, st_per_min):
    curr_row = which_row+((which_rep-1)*16)
    num_st_in_row = venus_rising_df.loc[curr_row,f"Chart {which_chart}"]
    msg = f"For row {which_row}, rep {which_rep}, in Chart {which_chart}:\nNum stitches: {num_st_in_row}, num minutes: {round(num_st_in_row/st_per_min,2)}"
    print(msg)

In [200]:
def explain(df):
    num_days = len(venus_log_df['Date'].drop_duplicates())
    first_row = venus_log_df.loc[0,:]
    last_row = venus_log_df.loc[venus_log_df.last_valid_index(),:]
    
    msgs = []
    msgs += [f"You've logged {num_days} days worth of work on the Venus Rising Shawl."]
    msgs += ["-------"]
    msgs += [f"You first logged work up to Chart {first_row['Chart']}, Rep {first_row['Rep']}, Row {first_row['Row']}."]
    msgs += [f"You are currently on Chart {last_row['Chart']}, Rep {last_row['Rep']}, Row {last_row['Row']}."]
    msgs += ["-------"]
    msgs += [f"You've completed {int(last_row['Completed (st)'])} stitches, which comprises {last_row['Completed (perc)']}% of the shawl."]
    msgs += [f"Given your last reported speed of {int(last_row['St/Min'])} st/min, this has taken you a total of roughly {int(last_row['Completed (hrs)'])} hours."]
    msgs += ["-------"]
    msgs += [f"You have {int(last_row['Remaining (st)'])} stitches left, which means {last_row['Remaining (perc)']}% of the shawl remains."]
    msgs += [f"Again, assuming {int(last_row['St/Min'])} st/min, this will take roughly {int(last_row['Remaining (hrs)'])} more hours."]
    msgs += ["-------"]
    full_msg = '\n'.join(msgs)
    print(full_msg)

## Venus Rising Calculator
This will generate information on how many st/min you have completed as well as left in your Venus Rising shawl.
Notes:
1. This calculator assumes that your knitting speed does not change. While this pattern does include stitches of varying complexity, this is just mant to be a rough estimate.
2. "which_row" represents the last row you completed. It will be included in the finished portion of the calculations.
3. This will not work for any rows *prior to* Chart 1, Row 1.

In [204]:
file_path = 'venus_log.csv'
file_exists = exists(file_path)

if not file_exists:
    print("file doesn't exist")
    cols = ['Date','Chart','Rep','Row','St/Min','Pattern (st)','Pattern (hrs)',
            'Completed (st)','Completed (hrs)','Completed (perc)',
            'Remaining (st)','Remaining (hrs)','Remaining (perc)','timestamp']
    df = pd.DataFrame(columns=['Date','Chart','Rep','Row','timestamp'])
    df.to_csv('venus_log.csv', index=False)

q = input("Do you want to A) save progress or B) ask about your next row? (A or B): ")

# ---------------------
# change this if I want
st_per_min = 14#int(input('ST/MIN: How many st per min?: ')) #20
# ---------------------

if q == 'A':
    venus_log_df = pd.read_csv('venus_log.csv')
    which_date = input('DATE: What date are you submitting this information for?\n(YYYY-MM-DD format or just hit enter for TODAY): ')
    which_date = which_date if which_date != '' else str(pd.Timestamp.now().date())
    which_chart = int(input('CHART: Which chart are you working on?: '))
    which_rep = int(input('REP: What repetition is this?: '))
    which_row = int(input('ROW: What row did you last finish?: '))

    print("----------\n")
    stats = calculate_progress(which_date, which_chart, which_rep, which_row, st_per_min)
    
    venus_log_df = venus_log_df.append(stats, ignore_index = True).drop_duplicates()
    venus_log_df.to_csv('venus_log.csv',index=False)
    explain(venus_log_df)

elif q == 'B':
    which_chart = int(input('CHART: Which chart are you curious about?: '))
    which_rep = int(input('REP: What repetition are you curious about?: '))
    which_row = int(input('ROW: What row are you curious about?: '))
    
    print("----------\n")
    give_me_info_on(which_chart, which_rep, which_row, st_per_min)

Do you want to A) save progress or B) ask about your next row? (A or B): A
DATE: What date are you submitting this information for?
(YYYY-MM-DD format or just hit enter for TODAY):
CHART: Which chart are you working on?: 6
REP: What repetition is this?: 1
ROW: What row did you last finish?: 10
----------

You've logged 10 days worth of work on the Venus Rising Shawl.
-------
You first logged work up to Chart 2, Rep 3, Row 4.
You are currently on Chart 6, Rep 1, Row 10.
-------
You've completed 18105 stitches, which comprises 67.82% of the shawl.
Given your last reported speed of 14 st/min, this has taken you a total of roughly 21 hours.
-------
You have 8590 stitches left, which means 32.18% of the shawl remains.
Again, assuming 14 st/min, this will take roughly 10 more hours.
-------

In [202]:
venus_log_df

,Date,Chart,Rep,Row,timestamp,Completed (hrs),Completed (perc),Completed (st),Pattern (hrs),Pattern (st),Remaining (hrs),Remaining (perc),Remaining (st),St/Min
0,2022-03-29,2,3,4,2022-03-30 20:52:19.902269,3.0,15.63,4068.0,21.0,26035.0,18.0,84.37,21967.0,20.0
1,2022-03-30,2,3,9,2022-03-30 20:53:17.742191,4.0,18.76,4885.0,21.0,26035.0,17.0,81.24,21150.0,20.0
2,2022-03-30,2,3,12,2022-03-30 22:03:34.636235,4.0,20.79,5412.0,21.0,26035.0,17.0,79.21,20623.0,20.0
3,2022-04-04,2,3,16,2022-04-04 17:10:18.350777,4.0,22.91,5965.0,21.0,26035.0,16.0,77.09,20070.0,20.0
4,2022-04-14,4,1,3,2022-04-14 19:16:30.519731,8.0,39.73,10345.0,21.0,26035.0,13.0,60.27,15690.0,20.0
5,2022-04-14,4,1,5,2022-04-14 20:16:12.960973,9.0,41.67,10849.0,21.0,26035.0,12.0,58.33,15186.0,20.0
6,2022-04-15,5,1,1,2022-04-15 19:54:43.727505,9.0,45.68,11893.0,21.0,26035.0,11.0,54.32,14142.0,20.0
7,2022-04-16,5,1,3,2022-04-16 22:47:21.113032,10.0,47.75,12433.0,21.0,26035.0,11.0,52.25,13602.0,20.0
8,2022-04-16,5,1,4,2022-04-16 23:14:13.984821,15.0,48.81,12708.0,30.0,26035.0,15.0,51.19,13327.0,14.0
9,2022-04-18,5,1,8,2022-04-18 22:37:00.741577,16.0,53.15,13838.0,30.0,26035.0,14.0,46.85,12197.0,14.0
10,2022-04-19,5,1,9,2022-04-19 11:13:49.355851,16.0,54.27,14129.0,30.0,26035.0,14.0,45.73,11906.0,14.0
11,2022-04-19,5,1,10,2022-04-19 20:36:02.013666,17.0,55.41,14426.0,30.0,26035.0,13.0,44.59,11609.0,14.0
12,2022-04-20,6,1,2,2022-04-20 17:52:05.961344,18.0,60.08,15642.0,30.0,26035.0,12.0,39.92,10393.0,14.0
13,2022-04-20,6,1,6,2022-04-20 22:17:27.795018,20.0,64.94,16906.0,30.0,26035.0,10.0,35.06,9129.0,14.0
14,2022-04-20,6,1,6,2022-04-20 22:47:25.164237,20.0,64.04,17096.0,31.0,26695.0,11.0,35.96,9599.0,14.0
15,2022-04-20,6,1,6,2022-04-20 22:50:37.706707,20.0,64.04,17096.0,31.0,26695.0,11.0,35.96,9599.0,14.0

In [160]:
all_rows_df = venus_rising_df.reset_index().melt(id_vars='index', value_vars=venus_rising_df.columns)

In [161]:
all_rows_df = all_rows_df.rename(columns={'index':'Row',
                                         'variable':'Chart',
                                            'value':'Sts'})
non_zero_rows_df = all_rows_df[all_rows_df['Sts'] != 0].reset_index(drop=True)[['Chart','Row','Sts']]

In [162]:
non_zero_rows_df['Running Total'] = non_zero_rows_df['Sts'].cumsum()

In [163]:
non_zero_rows_df['Running Percentage'] = non_zero_rows_df['Running Total'].apply(lambda x: str(round(100*x/max(non_zero_rows_df['Running Total']),2))+"%")

In [203]:
non_zero_rows_df

          Chart  Row  Sts  Running Total Running Percentage
0     Base Calc    0   36             36              0.13%
1     Base Calc    1   13             49              0.18%
2       Chart 1    0   17             66              0.25%
3       Chart 1    1   19             85              0.32%
4       Chart 1    2   23            108               0.4%
5       Chart 1    3   25            133               0.5%
6       Chart 1    4   29            162              0.61%
7       Chart 1    5   31            193              0.72%
8       Chart 1    6   35            228              0.85%
9       Chart 1    7   37            265              0.99%
10      Chart 1    8   41            306              1.15%
11      Chart 1    9   43            349              1.31%
12      Chart 2    0   47            396              1.48%
13      Chart 2    1   49            445              1.67%
14      Chart 2    2   53            498              1.87%
15      Chart 2    3   55            553              2.07%
16      Chart 2    4   59            612              2.29%
17      Chart 2    5   61            673              2.52%
18      Chart 2    6   65            738              2.76%
19      Chart 2    7   67            805              3.02%
20      Chart 2    8   71            876              3.28%
21      Chart 2    9   73            949              3.55%
22      Chart 2   10   77           1026              3.84%
23      Chart 2   11   79           1105              4.14%
24      Chart 2   12   83           1188              4.45%
25      Chart 2   13   85           1273              4.77%
26      Chart 2   14   89           1362               5.1%
27      Chart 2   15   91           1453              5.44%
28      Chart 2   16   95           1548               5.8%
29      Chart 2   17   97           1645              6.16%
30      Chart 2   18  101           1746              6.54%
31      Chart 2   19  103           1849              6.93%
32      Chart 2   20  107           1956              7.33%
33      Chart 2   21  109           2065              7.74%
34      Chart 2   22  113           2178              8.16%
35      Chart 2   23  115           2293              8.59%
36      Chart 2   24  119           2412              9.04%
37      Chart 2   25  121           2533              9.49%
38      Chart 2   26  125           2658              9.96%
39      Chart 2   27  127           2785             10.43%
40      Chart 2   28  131           2916             10.92%
41      Chart 2   29  133           3049             11.42%
42      Chart 2   30  137           3186             11.93%
43      Chart 2   31  139           3325             12.46%
44      Chart 2   32  143           3468             12.99%
45      Chart 2   33  145           3613             13.53%
46      Chart 2   34  149           3762             14.09%
47      Chart 2   35  151           3913             14.66%
48      Chart 2   36  155           4068             15.24%
49      Chart 2   37  157           4225             15.83%
50      Chart 2   38  161           4386             16.43%
51      Chart 2   39  163           4549             17.04%
52      Chart 2   40  167           4716             17.67%
53      Chart 2   41  169           4885              18.3%
54      Chart 2   42  173           5058             18.95%
55      Chart 2   43  175           5233              19.6%
56      Chart 2   44  179           5412             20.27%
57      Chart 2   45  181           5593             20.95%
58      Chart 2   46  185           5778             21.64%
59      Chart 2   47  187           5965             22.35%
60      Chart 3    0  191           6156             23.06%
61      Chart 3    1  193           6349             23.78%
62      Chart 3    2  197           6546             24.52%
63      Chart 3    3  199           6745             25.27%
64      Chart 3    4  203           6948             26.03%
65      Chart 3    5  205           7153              26.8%
66      Chart 3    6  209           7362             27.58%
67      Chart 3    7  211           7573             28.37%
68      Chart 3    8  215           7788             29.17%
69      Chart 3    9  217           8005             29.99%
70      Chart 3   10  221           8226             30.81%
71      Chart 3   11  223           8449             31.65%
72      Chart 3   12  227           8676              32.5%
73      Chart 3   13  229           8905             33.36%
74      Chart 3   14  233           9138             34.23%
75      Chart 3   15  235           9373             35.11%
76      Chart 4    0  239           9612             36.01%
77      Chart 4    1  241           9853             36.91%
78      Chart 4    2  245          10098             37.83%
79      Chart 4    3  247          10345             38.75%
80      Chart 4    4  251          10596             39.69%
81      Chart 4    5  253          10849             40.64%
82      Chart 4    6  257          11106              41.6%
83      Chart 4    7  259          11365             42.57%
84      Chart 5    0  273          11638              43.6%
85      Chart 5    1  275          11913             44.63%
86      Chart 5    2  279          12192             45.67%
87      Chart 5    3  281          12473             46.72%
88      Chart 5    4  285          12758             47.79%
89      Chart 5    5  287          13045             48.87%
90      Chart 5    6  291          13336             49.96%
91      Chart 5    7  293          13629             51.05%
92      Chart 5    8  299          13928             52.17%
93      Chart 5    9  301          14229              53.3%
94      Chart 5   10  307          14536             54.45%
95      Chart 5   11  309          14845             55.61%
96      Chart 6    0  313          15158             56.78%
97      Chart 6    1  315          15473             57.96%
98      Chart 6    2  319          15792             59.16%
99      Chart 6    3  321          16113             60.36%
100     Chart 6    4  325          16438             61.58%
101     Chart 6    5  327          16765              62.8%
102     Chart 6    6  331          17096             64.04%
103     Chart 6    7  333          17429             65.29%
104     Chart 6    8  337          17766             66.55%
105     Chart 6    9  339          18105             67.82%
106     Chart 7    0  353          18458             69.14%
107     Chart 7    1  355          18813             70.47%
108     Chart 7    2  359          19172             71.82%
109     Chart 7    3  363          19535             73.18%
110     Chart 7    4  367          19902             74.55%
111     Chart 7    5  369          20271             75.94%
112     Chart 7    6  373          20644             77.33%
113     Chart 7    7  379          21023             78.75%
114     Chart 7    8  383          21406             80.19%
115     Chart 7    9  387          21793             81.64%
116     Chart 7   10  393          22186             83.11%
117     Chart 7   11  395          22581             84.59%
118     Chart 7   12  399          22980             86.08%
119     Chart 7   13  401          23381             87.59%
120     Chart 7   14  405          23786              89.1%
121     Chart 7   15  407          24193             90.63%
122     Chart 7   16  411          24604             92.17%
123     Chart 7   17  413          25017             93.71%
124     Chart 7   18  417          25434             95.28%
125     Chart 7   19  419          25853             96.85%
126     Chart 7   20  421          26274             98.42%
127  Final Calc    0  421          26695             100.0%

In [147]:
venus_log_df

,Date,Chart,Rep,Row,timestamp,Completed (hrs),Completed (perc),Completed (st),Pattern (hrs),Pattern (st),Remaining (hrs),Remaining (perc),Remaining (st),St/Min
0,2022-03-29,2,3,4,2022-03-30 20:52:19.902269,3.0,15.63,4068.0,21.0,26035.0,18.0,84.37,21967.0,20.0
1,2022-03-30,2,3,9,2022-03-30 20:53:17.742191,4.0,18.76,4885.0,21.0,26035.0,17.0,81.24,21150.0,20.0
2,2022-03-30,2,3,12,2022-03-30 22:03:34.636235,4.0,20.79,5412.0,21.0,26035.0,17.0,79.21,20623.0,20.0
3,2022-04-04,2,3,16,2022-04-04 17:10:18.350777,4.0,22.91,5965.0,21.0,26035.0,16.0,77.09,20070.0,20.0
4,2022-04-14,4,1,3,2022-04-14 19:16:30.519731,8.0,39.73,10345.0,21.0,26035.0,13.0,60.27,15690.0,20.0
5,2022-04-14,4,1,5,2022-04-14 20:16:12.960973,9.0,41.67,10849.0,21.0,26035.0,12.0,58.33,15186.0,20.0
6,2022-04-15,5,1,1,2022-04-15 19:54:43.727505,9.0,45.68,11893.0,21.0,26035.0,11.0,54.32,14142.0,20.0
7,2022-04-16,5,1,3,2022-04-16 22:47:21.113032,10.0,47.75,12433.0,21.0,26035.0,11.0,52.25,13602.0,20.0
8,2022-04-16,5,1,4,2022-04-16 23:14:13.984821,15.0,48.81,12708.0,30.0,26035.0,15.0,51.19,13327.0,14.0
9,2022-04-18,5,1,8,2022-04-18 22:37:00.741577,16.0,53.15,13838.0,30.0,26035.0,14.0,46.85,12197.0,14.0
10,2022-04-19,5,1,9,2022-04-19 11:13:49.355851,16.0,54.27,14129.0,30.0,26035.0,14.0,45.73,11906.0,14.0
11,2022-04-19,5,1,10,2022-04-19 20:36:02.013666,17.0,55.41,14426.0,30.0,26035.0,13.0,44.59,11609.0,14.0
12,2022-04-20,6,1,2,2022-04-20 17:52:05.961344,18.0,60.08,15642.0,30.0,26035.0,12.0,39.92,10393.0,14.0
13,2022-04-20,6,1,6,2022-04-20 22:17:27.795018,20.0,64.94,16906.0,30.0,26035.0,10.0,35.06,9129.0,14.0

In [110]:
row_counts = {x:500+(3*x) for x in range(1,22)}
row_counts

{1: 503,
 2: 506,
 3: 509,
 4: 512,
 5: 515,
 6: 518,
 7: 521,
 8: 524,
 9: 527,
 10: 530,
 11: 533,
 12: 536,
 13: 539,
 14: 542,
 15: 545,
 16: 548,
 17: 551,
 18: 554,
 19: 557,
 20: 560,
 21: 563}

In [134]:
xx = [v for k,v in row_counts.items()]

In [165]:
sum(xx)

11193

In [144]:
# odd rows
num_odd_st = sum([v for k,v in row_counts.items() if k % 2 == 1])
odd_st_min = 10
odd_row_calc = (((num_odd_st / odd_st_min)/60)/11)*60
odd_row_calc

53.3

In [145]:
# even rows
num_even_st = sum([v for k,v in row_counts.items() if k % 2 == 0])
even_st_min = 14
even_row_calc = (((num_even_st / even_st_min)/60)/10)*60
even_row_calc

38.07142857142858

In [146]:
(odd_row_calc + even_row_calc)/2

45.68571428571428

In [148]:
sum(xx)

11193

In [149]:
9129.0

9129.0

In [150]:
venus_rising_df

,Base Calc,Chart 1,Chart 2,Chart 3,Chart 4,Chart 5,Chart 6,Chart 7,Final Calc
0,36,17,47,191,239,263,303,333,401
1,13,19,49,193,241,265,305,335,0
2,0,23,53,197,245,269,309,339,0
3,0,25,55,199,247,271,311,343,0
4,0,29,59,203,251,275,315,347,0
5,0,31,61,205,253,277,317,349,0
6,0,35,65,209,257,281,321,353,0
7,0,37,67,211,259,283,323,359,0
8,0,41,71,215,0,289,327,363,0
9,0,43,73,217,0,291,329,367,0
10,0,0,77,221,0,297,0,373,0
11,0,0,79,223,0,299,0,375,0
12,0,0,83,227,0,0,0,379,0
13,0,0,85,229,0,0,0,381,0
14,0,0,89,233,0,0,0,385,0
15,0,0,91,235,0,0,0,387,0
16,0,0,95,0,0,0,0,391,0
17,0,0,97,0,0,0,0,393,0
18,0,0,101,0,0,0,0,397,0
19,0,0,103,0,0,0,0,399,0
20,0,0,107,0,0,0,0,401,0
21,0,0,109,0,0,0,0,0,0
22,0,0,113,0,0,0,0,0,0
23,0,0,115,0,0,0,0,0,0
24,0,0,119,0,0,0,0,0,0
25,0,0,121,0,0,0,0,0,0
26,0,0,125,0,0,0,0,0,0
27,0,0,127,0,0,0,0,0,0
28,0,0,131,0,0,0,0,0,0
29,0,0,133,0,0,0,0,0,0
30,0,0,137,0,0,0,0,0,0
31,0,0,139,0,0,0,0,0,0
32,0,0,143,0,0,0,0,0,0
33,0,0,145,0,0,0,0,0,0
34,0,0,149,0,0,0,0,0,0
35,0,0,151,0,0,0,0,0,0
36,0,0,155,0,0,0,0,0,0
37,0,0,157,0,0,0,0,0,0
38,0,0,161,0,0,0,0,0,0
39,0,0,163,0,0,0,0,0,0
40,0,0,167,0,0,0,0,0,0
41,0,0,169,0,0,0,0,0,0
42,0,0,173,0,0,0,0,0,0
43,0,0,175,0,0,0,0,0,0
44,0,0,179,0,0,0,0,0,0
45,0,0,181,0,0,0,0,0,0
46,0,0,185,0,0,0,0,0,0
47,0,0,187,0,0,0,0,0,0